In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
from nltk.tokenize import RegexpTokenizer
import pandas as pd
from nltk.tokenize import RegexpTokenizer
import nltk.corpus as Corpus

In [ ]:
data = pd.read_csv(r"/content/drive/MyDrive/coca_5_grams (1).csv")

In [ ]:
data.head()

Unnamed: 0           sentences
0           0    i do n't want to
1           1   at the end of the
2           2  i do n't know what
3           3  you do n't have to
4           4    i do n't know if

In [ ]:
data

Unnamed: 0                      sentences
0                 0               i do n't want to
1                 1              at the end of the
2                 2             i do n't know what
3                 3             you do n't have to
4                 4               i do n't know if
...             ...                            ...
5782182     5782182  zones of iraq and afghanistan
5782183     5782183     zones that they should not
5782184     5782184          zoo and the san diego
5782185     5782185       zoo in the united states
5782186     5782186            zoo is home to more

[5782187 rows x 2 columns]

In [ ]:
data = data[:5000]

In [ ]:
import numpy as np
import pandas as pd
import os
import re

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.layers import Dense,LSTM,Embedding
from tensorflow.keras.preprocessing.text import Tokenizer 
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

In [ ]:
pwd

'/content'

In [ ]:
data = data[:5000]

In [ ]:
data

Unnamed: 0              sentences
0              0       i do n't want to
1              1      at the end of the
2              2     i do n't know what
3              3     you do n't have to
4              4       i do n't know if
...          ...                    ...
4995        4995    do you think is the
4996        4996    from one end of the
4997        4997  have an impact on the
4998        4998   i will tell you that
4999        4999  in the sense that the

[5000 rows x 2 columns]

In [ ]:
text = data["sentences"]

In [ ]:
text

0            i do n't want to
1           at the end of the
2          i do n't know what
3          you do n't have to
4            i do n't know if
                ...          
4995      do you think is the
4996      from one end of the
4997    have an impact on the
4998     i will tell you that
4999    in the sense that the
Name: sentences, Length: 5000, dtype: object

In [ ]:
text = text.str.lower()

In [ ]:
tokenizer = Tokenizer(oov_token='<oov>')

In [ ]:
tokenizer.fit_on_texts(text)

In [ ]:
print('word_index :',tokenizer.word_index)

word_index : {'<oov>': 1, 'the': 2, 'to': 3, 'of': 4, "n't": 5, 'do': 6, 'i': 7, 'you': 8, 'a': 9, 'have': 10, 'that': 11, 'it': 12, 'be': 13, 'is': 14, 'in': 15, 'want': 16, 'know': 17, 'and': 18, 'what': 19, 'for': 20, 'was': 21, 'did': 22, 'going': 23, 'think': 24, 'are': 25, 'at': 26, 'we': 27, 'time': 28, 'this': 29, 'as': 30, 'with': 31, 'get': 32, 'on': 33, 'if': 34, 'one': 35, 'lot': 36, 'not': 37, 'about': 38, 'way': 39, 'out': 40, 'there': 41, 'would': 42, 'he': 43, 'how': 44, 'me': 45, 'does': 46, 'ca': 47, 'just': 48, 'able': 49, 'like': 50, 'can': 51, 'end': 52, 'but': 53, 'they': 54, 'united': 55, 'make': 56, 'first': 57, 'all': 58, 'who': 59, 'go': 60, 'tell': 61, 'people': 62, 'na': 63, 'back': 64, 'see': 65, 'need': 66, 'states': 67, 'say': 68, 'take': 69, 'no': 70, 'rest': 71, 'long': 72, 'years': 73, 'why': 74, 'has': 75, 'part': 76, 'been': 77, 'much': 78, 'from': 79, 'fact': 80, 'thing': 81, 'talk': 82, 'over': 83, 'more': 84, 'gon': 85, 'anything': 86, 'so': 87, '

In [ ]:
sequences = tokenizer.texts_to_sequences(text)

In [ ]:
sequences

[[7, 6, 5, 16, 3],
 [26, 2, 52, 4, 2],
 [7, 6, 5, 17, 19],
 [8, 6, 5, 10, 3],
 [7, 6, 5, 17, 34],
 [15, 2, 130, 4, 2],
 [8, 6, 5, 16, 3],
 [7, 6, 5, 17, 44],
 [7, 6, 5, 24, 12],
 [7, 6, 5, 24, 11],
 [182, 4, 2, 55, 67],
 [7, 6, 5, 24, 87],
 [41, 25, 9, 36, 4],
 [7, 6, 5, 24, 7],
 [20, 2, 57, 28, 15],
 [19, 25, 8, 227, 38],
 [7, 22, 5, 16, 3],
 [2, 93, 104, 4, 2],
 [19, 25, 8, 177, 111],
 [6, 5, 16, 3, 13],
 [2, 52, 4, 2, 171],
 [7, 6, 5, 17, 74],
 [33, 2, 93, 104, 4],
 [133, 2, 52, 4, 2],
 [53, 7, 6, 5, 24],
 [75, 146, 3, 6, 31],
 [2, 71, 4, 2, 128],
 [26, 2, 136, 4, 2],
 [7, 6, 5, 147, 63],
 [7, 6, 5, 24, 8],
 [7, 6, 5, 10, 3],
 [14, 35, 4, 2, 89],
 [7, 6, 5, 10, 9],
 [6, 5, 17, 19, 3],
 [18, 7, 6, 5, 24],
 [8, 17, 19, 7, 106],
 [7, 6, 5, 24, 27],
 [6, 5, 17, 44, 3],
 [35, 4, 2, 116, 11],
 [7, 6, 5, 24, 43],
 [30, 9, 107, 4, 80],
 [6, 5, 17, 19, 8],
 [190, 8, 87, 78, 20],
 [7, 6, 5, 100, 17],
 [6, 8, 16, 45, 3],
 [2, 182, 4, 2, 55],
 [18, 7, 6, 5, 17],
 [90, 146, 3, 6, 31],
 [15, 2, 1

In [ ]:
len(sequences)

5000

In [ ]:
total_words = len(tokenizer.word_index) + 1

In [ ]:
print("Total number of words: ", total_words)

Total number of words:  1161


In [ ]:
input_sequences = []
for line in data['sentences']:
    token_list = tokenizer.texts_to_sequences([line])[0]   
    print(token_list)

[7, 6, 5, 16, 3]
[26, 2, 52, 4, 2]
[7, 6, 5, 17, 19]
[8, 6, 5, 10, 3]
[7, 6, 5, 17, 34]
[15, 2, 130, 4, 2]
[8, 6, 5, 16, 3]
[7, 6, 5, 17, 44]
[7, 6, 5, 24, 12]
[7, 6, 5, 24, 11]
[182, 4, 2, 55, 67]
[7, 6, 5, 24, 87]
[41, 25, 9, 36, 4]
[7, 6, 5, 24, 7]
[20, 2, 57, 28, 15]
[19, 25, 8, 227, 38]
[7, 22, 5, 16, 3]
[2, 93, 104, 4, 2]
[19, 25, 8, 177, 111]
[6, 5, 16, 3, 13]
[2, 52, 4, 2, 171]
[7, 6, 5, 17, 74]
[33, 2, 93, 104, 4]
[133, 2, 52, 4, 2]
[53, 7, 6, 5, 24]
[75, 146, 3, 6, 31]
[2, 71, 4, 2, 128]
[26, 2, 136, 4, 2]
[7, 6, 5, 147, 63]
[7, 6, 5, 24, 8]
[7, 6, 5, 10, 3]
[14, 35, 4, 2, 89]
[7, 6, 5, 10, 9]
[6, 5, 17, 19, 3]
[18, 7, 6, 5, 24]
[8, 17, 19, 7, 106]
[7, 6, 5, 24, 27]
[6, 5, 17, 44, 3]
[35, 4, 2, 116, 11]
[7, 6, 5, 24, 43]
[30, 9, 107, 4, 80]
[6, 5, 17, 19, 8]
[190, 8, 87, 78, 20]
[7, 6, 5, 100, 17]
[6, 8, 16, 45, 3]
[2, 182, 4, 2, 55]
[18, 7, 6, 5, 17]
[90, 146, 3, 6, 31]
[15, 2, 130, 4, 9]
[2, 130, 4, 2, 331]
[151, 5, 13, 49, 3]
[30, 9, 245, 4, 2]
[27, 6, 5, 16, 3]
[54, 6, 5,

In [ ]:
len(token_list)

5

In [ ]:
input_sequences = []
for line in data['sentences']:
    token_list = tokenizer.texts_to_sequences([line])[0]    
#    for i in range(1, len(token_list)):
#        n_gram_sequence = token_list[:i+1]
    input_sequences.append(token_list)
print("Total input sequences: ", len(input_sequences))

Total input sequences:  5000


In [ ]:
max_sequence_len = max([len(x) for x in input_sequences])
print(max_sequence_len)

6


In [ ]:
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))

In [ ]:
print(input_sequences)

[[   0    7    6    5   16    3]
 [   0   26    2   52    4    2]
 [   0    7    6    5   17   19]
 ...
 [   0   10   97 1160   33    2]
 [   0    7   96   61    8   11]
 [   0   15    2  193   11    2]]


In [ ]:
len(input_sequences)

5000

In [ ]:
xs, labels = input_sequences[:,:-1],input_sequences[:,-1]

In [ ]:
print(xs)

[[   0    7    6    5   16]
 [   0   26    2   52    4]
 [   0    7    6    5   17]
 ...
 [   0   10   97 1160   33]
 [   0    7   96   61    8]
 [   0   15    2  193   11]]


In [ ]:
xs.shape

(5000, 5)

In [ ]:
print(labels)

[ 3  2 19 ...  2 11  2]


In [ ]:
!pip install category_encoders

In [ ]:
#ys = tf.keras.utils.to_categorical(labels, num_classes=total_words)

In [ ]:
ys = np.array(labels)

In [ ]:
ys.shape

(5000,)

In [ ]:
ys[:]

array([ 3,  2, 19, ...,  2, 11,  2], dtype=int32)

In [ ]:
ys.shape

(5000,)

In [ ]:
len(ys)

5000

In [ ]:
print(xs[5])
print(labels[5])


[  0  15   2 130   4]
2


In [ ]:
#input clear

In [ ]:
type(xs)

numpy.ndarray

In [ ]:
type(ys)

numpy.ndarray

In [ ]:
xs.shape

(5000, 5)

In [ ]:
ys.shape

(5000,)

In [ ]:
data

Unnamed: 0              sentences
0              0       i do n't want to
1              1      at the end of the
2              2     i do n't know what
3              3     you do n't have to
4              4       i do n't know if
...          ...                    ...
4995        4995    do you think is the
4996        4996    from one end of the
4997        4997  have an impact on the
4998        4998   i will tell you that
4999        4999  in the sense that the

[5000 rows x 2 columns]

In [ ]:
data = data[["sentences"]]

In [ ]:
len(data)

5000

In [ ]:
import nltk
from nltk.tokenize import word_tokenize

In [ ]:
def create_tokens(data):   
    sent_tokens =[]
    word_tokens = []
    for i in range(len(data)):
        word_tokens.append(word_tokenize(data[i]))
        sent_tokens.append(word_tokens[i])
    return sent_tokens

In [ ]:
a=data["sentences"].tolist()

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
a=create_tokens(a)  
len(a)

5000

In [ ]:
a

[['i', 'do', "n't", 'want', 'to'],
 ['at', 'the', 'end', 'of', 'the'],
 ['i', 'do', "n't", 'know', 'what'],
 ['you', 'do', "n't", 'have', 'to'],
 ['i', 'do', "n't", 'know', 'if'],
 ['in', 'the', 'middle', 'of', 'the'],
 ['you', 'do', "n't", 'want', 'to'],
 ['i', 'do', "n't", 'know', 'how'],
 ['i', 'do', "n't", 'think', 'it'],
 ['i', 'do', "n't", 'think', 'that'],
 ['president', 'of', 'the', 'united', 'states'],
 ['i', 'do', "n't", 'think', 'so'],
 ['there', 'are', 'a', 'lot', 'of'],
 ['i', 'do', "n't", 'think', 'i'],
 ['for', 'the', 'first', 'time', 'in'],
 ['what', 'are', 'you', 'talking', 'about'],
 ['i', 'did', "n't", 'want', 'to'],
 ['the', 'other', 'side', 'of', 'the'],
 ['what', 'are', 'you', 'doing', 'here'],
 ['do', "n't", 'want', 'to', 'be'],
 ['the', 'end', 'of', 'the', 'day'],
 ['i', 'do', "n't", 'know', 'why'],
 ['on', 'the', 'other', 'side', 'of'],
 ['by', 'the', 'end', 'of', 'the'],
 ['but', 'i', 'do', "n't", 'think'],
 ['has', 'nothing', 'to', 'do', 'with'],
 ['the', 're

In [ ]:
type(a)

list

In [ ]:
len(a)

5000

In [ ]:
a[0][-1]

'to'

In [ ]:
last_word = []
for i in range(5000):
  a[i][-1]
  last_word.append(a[i][-1])
  

In [ ]:
last_word

['to',
 'the',
 'what',
 'to',
 'if',
 'the',
 'to',
 'how',
 'it',
 'that',
 'states',
 'so',
 'of',
 'i',
 'in',
 'about',
 'to',
 'the',
 'here',
 'be',
 'day',
 'why',
 'of',
 'the',
 'think',
 'with',
 'world',
 'the',
 'na',
 'you',
 'to',
 'most',
 'a',
 'to',
 'think',
 'mean',
 'we',
 'to',
 'that',
 'he',
 'fact',
 'you',
 'for',
 'know',
 'to',
 'united',
 'know',
 'with',
 'a',
 'night',
 'to',
 'the',
 'to',
 'to',
 'the',
 'the',
 'the',
 'the',
 'do',
 'time',
 'you',
 'what',
 'have',
 'to',
 'know',
 'a',
 'to',
 'about',
 'the',
 'i',
 'there',
 'be',
 'where',
 'a',
 'want',
 'the',
 'that',
 'to',
 'just',
 'to',
 'any',
 'the',
 'america',
 'year',
 'be',
 'and',
 'since',
 'they',
 'to',
 'to',
 'you',
 'that',
 'the',
 'do',
 'what',
 'it',
 'na',
 'you',
 'i',
 'important',
 'the',
 'go',
 'the',
 'the',
 'of',
 'want',
 'to',
 'do',
 'the',
 'you',
 'to',
 'a',
 'the',
 'of',
 'the',
 'for',
 'the',
 'mean',
 'the',
 'of',
 'kid',
 'the',
 'the',
 'of',
 'time'

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
labelencoder = LabelEncoder()

In [ ]:
labels = labelencoder.fit_transform(last_word)

In [ ]:
labels

array([530, 516, 576, ..., 516, 515, 516])

In [ ]:
from sklearn import preprocessing
labels = preprocessing.normalize([labels])


In [ ]:
labels

array([[0.01827552, 0.01779277, 0.01986169, ..., 0.01779277, 0.01775829,
        0.01779277]])

In [ ]:
labels.shape

(1, 5000)

In [ ]:
#a = model[model.wv.vocab]

In [ ]:
len(a) 

5000

In [ ]:
a

[['i', 'do', "n't", 'want', 'to'],
 ['at', 'the', 'end', 'of', 'the'],
 ['i', 'do', "n't", 'know', 'what'],
 ['you', 'do', "n't", 'have', 'to'],
 ['i', 'do', "n't", 'know', 'if'],
 ['in', 'the', 'middle', 'of', 'the'],
 ['you', 'do', "n't", 'want', 'to'],
 ['i', 'do', "n't", 'know', 'how'],
 ['i', 'do', "n't", 'think', 'it'],
 ['i', 'do', "n't", 'think', 'that'],
 ['president', 'of', 'the', 'united', 'states'],
 ['i', 'do', "n't", 'think', 'so'],
 ['there', 'are', 'a', 'lot', 'of'],
 ['i', 'do', "n't", 'think', 'i'],
 ['for', 'the', 'first', 'time', 'in'],
 ['what', 'are', 'you', 'talking', 'about'],
 ['i', 'did', "n't", 'want', 'to'],
 ['the', 'other', 'side', 'of', 'the'],
 ['what', 'are', 'you', 'doing', 'here'],
 ['do', "n't", 'want', 'to', 'be'],
 ['the', 'end', 'of', 'the', 'day'],
 ['i', 'do', "n't", 'know', 'why'],
 ['on', 'the', 'other', 'side', 'of'],
 ['by', 'the', 'end', 'of', 'the'],
 ['but', 'i', 'do', "n't", 'think'],
 ['has', 'nothing', 'to', 'do', 'with'],
 ['the', 're

In [ ]:
from gensim.models import FastText

In [ ]:
model = FastText(a, window=3, size = 150, min_count = 1, alpha = 0.2, sg =1, hs = 1,max_vocab_size = None, iter=50, workers = 40) 

In [ ]:
a = model[model.wv.vocab]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


In [ ]:
len(a)

1159

In [ ]:
!pip install k-means-constrained

In [ ]:
from k_means_constrained import KMeansConstrained

In [ ]:
clf = KMeansConstrained(
     n_clusters=95,
     size_min=10,
     size_max=13,
     random_state=0,
)

In [ ]:
clf.fit_predict(a)

array([23, 29, 23, ..., 24, 25, 15], dtype=int32)

In [ ]:
y1 = clf.labels_

In [ ]:
words = list(model.wv.vocab)


In [ ]:
def call_cluster(words):
    ab = []
    a=[]
    for cl_name in range(0,145):
        for i, word in enumerate(words):
            if(y1[i]==cl_name):
            
                ab.append([cl_name,word])
    return ab    

In [ ]:
import pandas as pd

In [ ]:
b=call_cluster(words)

In [ ]:
b

[[0, 'understand'],
 [0, 'editor'],
 [0, 'understanding'],
 [0, 'pros'],
 [0, 'privacy'],
 [0, 'policy'],
 [0, 'editors'],
 [0, 'useful'],
 [0, 'findings'],
 [0, 'price'],
 [0, 'private'],
 [0, 'police'],
 [0, 'prime'],
 [1, 'edge'],
 [1, 'basis'],
 [1, 'size'],
 [1, 'opposite'],
 [1, 'spite'],
 [1, 'nail'],
 [1, 'piece'],
 [1, 'based'],
 [1, 'lookout'],
 [1, 'quite'],
 [1, 'topic'],
 [1, 'fourth'],
 [1, 'looked'],
 [2, 'states'],
 [2, 'start'],
 [2, 'state'],
 [2, 'staff'],
 [2, 'stages'],
 [2, 'stand'],
 [2, 'statistics'],
 [2, 'studies'],
 [2, 'hate'],
 [2, 'statement'],
 [2, 'stay'],
 [2, 'streets'],
 [2, 'started'],
 [3, 'food'],
 [3, 'church'],
 [3, 'season'],
 [3, 'pepper'],
 [3, 'taste'],
 [3, 'pain'],
 [3, 'grain'],
 [3, 'black'],
 [3, 'trouble'],
 [3, 'atomic'],
 [3, 'children'],
 [3, 'minister'],
 [3, 'highway'],
 [4, 'both'],
 [4, 'sides'],
 [4, 'street'],
 [4, 'aisle'],
 [4, 'bureau'],
 [4, 'banks'],
 [4, 'freedom'],
 [4, 'federal'],
 [4, 'female'],
 [4, 'male'],
 [4, 'kno

In [ ]:
len(b)

1159

In [ ]:
import pandas as pd

In [ ]:
df2=pd.DataFrame(b,columns=['cluster_no','words'])

In [ ]:
index=[]
for i in range(95):
  c=0
  for j in df2['cluster_no']:
    if(j==i):
      index.append(c)
      c=c+1
len(index)

1159

In [ ]:
index = np.array(index)
index.shape

(1159,)

In [ ]:
df2['cluster_index'] = index

In [ ]:
df2.head(50)

cluster_no          words  cluster_index
0            0     understand              0
1            0         editor              1
2            0  understanding              2
3            0           pros              3
4            0        privacy              4
5            0         policy              5
6            0        editors              6
7            0         useful              7
8            0       findings              8
9            0          price              9
10           0        private             10
11           0         police             11
12           0          prime             12
13           1           edge              0
14           1          basis              1
15           1           size              2
16           1       opposite              3
17           1          spite              4
18           1           nail              5
19           1          piece              6
20           1          based              7
21           1        lookout              8
22           1          quite              9
23           1          topic             10
24           1         fourth             11
25           1         looked             12
26           2         states              0
27           2          start              1
28           2          state              2
29           2          staff              3
30           2         stages              4
31           2          stand              5
32           2     statistics              6
33           2        studies              7
34           2           hate              8
35           2      statement              9
36           2           stay             10
37           2        streets             11
38           2        started             12
39           3           food              0
40           3         church              1
41           3         season              2
42           3         pepper              3
43           3          taste              4
44           3           pain              5
45           3          grain              6
46           3          black              7
47           3        trouble              8
48           3         atomic              9
49           3       children             10

In [ ]:
df2.shape

(1159, 3)

In [ ]:
y1

array([23, 29, 23, ..., 24, 25, 15], dtype=int32)

In [ ]:
labels

array([[0.01827552, 0.01779277, 0.01986169, ..., 0.01779277, 0.01775829,
        0.01779277]])

In [ ]:
labels.shape

(1, 5000)

In [ ]:
labels = labels.T


In [ ]:
labels.shape

(5000, 1)

In [ ]:
labels = labels.flatten()


In [ ]:
labels.shape

(5000,)

In [ ]:
#for time1 in df1['time']:
#        for time2 in df2['time']:
#            if time1==time2:
#                j=(df1[df1['time']==time].index.values.astype(int)[0])
#                df_temp=df1.iloc[j]
#                    df_new.append(df_temp)

In [ ]:
last_word

['to',
 'the',
 'what',
 'to',
 'if',
 'the',
 'to',
 'how',
 'it',
 'that',
 'states',
 'so',
 'of',
 'i',
 'in',
 'about',
 'to',
 'the',
 'here',
 'be',
 'day',
 'why',
 'of',
 'the',
 'think',
 'with',
 'world',
 'the',
 'na',
 'you',
 'to',
 'most',
 'a',
 'to',
 'think',
 'mean',
 'we',
 'to',
 'that',
 'he',
 'fact',
 'you',
 'for',
 'know',
 'to',
 'united',
 'know',
 'with',
 'a',
 'night',
 'to',
 'the',
 'to',
 'to',
 'the',
 'the',
 'the',
 'the',
 'do',
 'time',
 'you',
 'what',
 'have',
 'to',
 'know',
 'a',
 'to',
 'about',
 'the',
 'i',
 'there',
 'be',
 'where',
 'a',
 'want',
 'the',
 'that',
 'to',
 'just',
 'to',
 'any',
 'the',
 'america',
 'year',
 'be',
 'and',
 'since',
 'they',
 'to',
 'to',
 'you',
 'that',
 'the',
 'do',
 'what',
 'it',
 'na',
 'you',
 'i',
 'important',
 'the',
 'go',
 'the',
 'the',
 'of',
 'want',
 'to',
 'do',
 'the',
 'you',
 'to',
 'a',
 'the',
 'of',
 'the',
 'for',
 'the',
 'mean',
 'the',
 'of',
 'kid',
 'the',
 'the',
 'of',
 'time'

In [ ]:
#last_word = list(dict.fromkeys(last_word))

In [ ]:
#last_word

In [ ]:
cn = {df2['words'][i]:df2['cluster_no'][i] for i in range(len(df2['words']))}
cn

{'understand': 0,
 'editor': 0,
 'understanding': 0,
 'pros': 0,
 'privacy': 0,
 'policy': 0,
 'editors': 0,
 'useful': 0,
 'findings': 0,
 'price': 0,
 'private': 0,
 'police': 0,
 'prime': 0,
 'edge': 1,
 'basis': 1,
 'size': 1,
 'opposite': 1,
 'spite': 1,
 'nail': 1,
 'piece': 1,
 'based': 1,
 'lookout': 1,
 'quite': 1,
 'topic': 1,
 'fourth': 1,
 'looked': 1,
 'states': 2,
 'start': 2,
 'state': 2,
 'staff': 2,
 'stages': 2,
 'stand': 2,
 'statistics': 2,
 'studies': 2,
 'hate': 2,
 'statement': 2,
 'stay': 2,
 'streets': 2,
 'started': 2,
 'food': 3,
 'church': 3,
 'season': 3,
 'pepper': 3,
 'taste': 3,
 'pain': 3,
 'grain': 3,
 'black': 3,
 'trouble': 3,
 'atomic': 3,
 'children': 3,
 'minister': 3,
 'highway': 3,
 'both': 4,
 'sides': 4,
 'street': 4,
 'aisle': 4,
 'bureau': 4,
 'banks': 4,
 'freedom': 4,
 'federal': 4,
 'female': 4,
 'male': 4,
 'knock': 4,
 'rock': 4,
 'roll': 4,
 'benefit': 5,
 'hope': 5,
 'canada': 5,
 'senate': 5,
 'clue': 5,
 'die': 5,
 'development': 5,

In [ ]:
cin = {df2['words'][i]:df2['cluster_index'][i] for i in range(len(df2['words']))}
cin

{'understand': 0,
 'editor': 1,
 'understanding': 2,
 'pros': 3,
 'privacy': 4,
 'policy': 5,
 'editors': 6,
 'useful': 7,
 'findings': 8,
 'price': 9,
 'private': 10,
 'police': 11,
 'prime': 12,
 'edge': 0,
 'basis': 1,
 'size': 2,
 'opposite': 3,
 'spite': 4,
 'nail': 5,
 'piece': 6,
 'based': 7,
 'lookout': 8,
 'quite': 9,
 'topic': 10,
 'fourth': 11,
 'looked': 12,
 'states': 0,
 'start': 1,
 'state': 2,
 'staff': 3,
 'stages': 4,
 'stand': 5,
 'statistics': 6,
 'studies': 7,
 'hate': 8,
 'statement': 9,
 'stay': 10,
 'streets': 11,
 'started': 12,
 'food': 0,
 'church': 1,
 'season': 2,
 'pepper': 3,
 'taste': 4,
 'pain': 5,
 'grain': 6,
 'black': 7,
 'trouble': 8,
 'atomic': 9,
 'children': 10,
 'minister': 11,
 'highway': 12,
 'both': 0,
 'sides': 1,
 'street': 2,
 'aisle': 3,
 'bureau': 4,
 'banks': 5,
 'freedom': 6,
 'federal': 7,
 'female': 8,
 'male': 9,
 'knock': 10,
 'rock': 11,
 'roll': 12,
 'benefit': 0,
 'hope': 1,
 'canada': 2,
 'senate': 3,
 'clue': 4,
 'die': 5,
 'd

In [ ]:
import time
t1 = time.time()
l=[]
ci=[]
for i in last_word:
  value1=cn.get(i)
  value2=cin.get(i)
  l.append(value1)
  ci.append(value2)
t2 = time.time()
print(t2-t1)

0.006805419921875


In [ ]:
len(l)

5000

In [ ]:
l

[54,
 74,
 44,
 54,
 23,
 74,
 54,
 36,
 44,
 44,
 2,
 48,
 17,
 23,
 53,
 44,
 54,
 74,
 33,
 64,
 74,
 75,
 17,
 74,
 28,
 48,
 17,
 74,
 75,
 38,
 54,
 52,
 33,
 54,
 28,
 71,
 85,
 54,
 44,
 85,
 72,
 38,
 45,
 71,
 54,
 27,
 71,
 48,
 33,
 35,
 54,
 74,
 54,
 54,
 74,
 74,
 74,
 74,
 29,
 63,
 38,
 44,
 34,
 54,
 71,
 33,
 54,
 44,
 74,
 23,
 33,
 64,
 33,
 33,
 75,
 74,
 44,
 54,
 69,
 54,
 82,
 74,
 80,
 69,
 64,
 87,
 63,
 36,
 54,
 54,
 38,
 44,
 74,
 29,
 44,
 44,
 75,
 38,
 23,
 53,
 74,
 75,
 74,
 74,
 17,
 75,
 54,
 29,
 74,
 38,
 54,
 33,
 74,
 17,
 74,
 45,
 74,
 71,
 74,
 17,
 29,
 74,
 74,
 17,
 63,
 31,
 17,
 74,
 29,
 44,
 74,
 23,
 38,
 44,
 64,
 29,
 54,
 22,
 88,
 17,
 74,
 74,
 54,
 33,
 64,
 75,
 54,
 70,
 44,
 23,
 74,
 64,
 74,
 29,
 54,
 74,
 54,
 74,
 63,
 48,
 38,
 72,
 17,
 54,
 44,
 33,
 54,
 44,
 34,
 44,
 64,
 44,
 74,
 33,
 75,
 29,
 44,
 44,
 74,
 54,
 50,
 74,
 54,
 74,
 87,
 23,
 88,
 54,
 23,
 74,
 71,
 78,
 44,
 74,
 33,
 23,
 31,
 94,
 33,
 54,
 

In [ ]:
ci

[0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 0,
 2,
 0,
 2,
 2,
 0,
 0,
 0,
 1,
 1,
 0,
 4,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 3,
 0,
 0,
 0,
 0,
 3,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 1,
 4,
 0,
 0,
 2,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 3,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 1,
 0,
 6,
 0,
 0,
 5,
 2,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 0,
 0,
 3,
 1,
 0,
 3,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 3,
 4,
 0,
 4,
 0,
 0,
 0,
 3,
 0,
 1,
 5,
 1,
 4,
 2,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 3,
 0,
 2,
 0,
 4,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 3,
 0,
 0,
 1,
 4,
 5,
 0,
 0,
 0,
 5,
 1,
 0,
 2,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 4,
 0,
 0,
 0,
 1,
 1,
 0,
 3,
 0,
 0,
 2,
 4,


In [ ]:
df2['cluster_no'][8]

0

In [ ]:
len(ci)

5000

In [ ]:
len(l)

5000

In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
#y2 = to_categorical(l, num_classes=95)

In [ ]:
y2 = np.array(l)

In [ ]:
y2

array([54, 74, 44, ..., 74, 44, 74])

In [ ]:
y2 = preprocessing.normalize([y2])


In [ ]:
y2.shape

(1, 5000)

In [ ]:
y2 = y2.flatten()
y2.shape

(5000,)

In [ ]:
#yi = to_categorical(ci, num_classes=13)
yi = np.array(ci)

In [ ]:
yi.shape

(5000,)

In [ ]:
xs

array([[   0,    7,    6,    5,   16],
       [   0,   26,    2,   52,    4],
       [   0,    7,    6,    5,   17],
       ...,
       [   0,   10,   97, 1160,   33],
       [   0,    7,   96,   61,    8],
       [   0,   15,    2,  193,   11]], dtype=int32)

In [ ]:
y2.shape

(5000,)

In [ ]:
xs.shape

(5000, 5)

In [ ]:
ys.shape

(5000,)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Concatenate
from tensorflow.keras.optimizers import RMSprop

In [ ]:
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()


In [ ]:
inputs = Input(shape=(5, ))
emb = Embedding(1200, 96, input_length=5000, trainable=True)
l0 = emb(inputs)
l0 = LSTM(500, return_sequences=True)(l0)
l0 = LSTM(200)(l0)
l0 = Dense(100, activation='tanh')(l0)
out1 = Dense(95, activation='softmax', name='cluster')(l0)
concatenated = Concatenate()([l0, out1])
out2 = Dense(13, activation='softmax', name='cluster_index')(concatenated)
model = Model(inputs=inputs, outputs=[out1, out2])

In [ ]:
#from tensorflow.keras.optimizers import Adam
#from tensorflow.keras.callbacks import EarlyStopping
#model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#earlystop = EarlyStopping(monitor='val_loss',min_delta=0,patience=3,verbose=1,mode='auto')

In [ ]:
from tensorflow.keras.optimizers import Adam
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(xs, [y2, yi], epochs = 2, batch_size =1)

Train on 5000 samples
Epoch 1/2
5000/5000 [==============================] - 152s 30ms/sample - loss: 1.7554 - cluster_loss: 0.0090 - cluster_index_loss: 1.7464 - cluster_acc: 0.0022 - cluster_index_acc: 0.5044
Epoch 2/2
5000/5000 [==============================] - 150s 30ms/sample - loss: 1.7432 - cluster_loss: 0.0030 - cluster_index_loss: 1.7402 - cluster_acc: 0.0022 - cluster_index_acc: 0.5024


In [ ]:
def get_cluster_LastWord(model, tokenizer, max_length, seed_text, n_words):
  in_text = seed_text
  for _ in range(n_words):
    encoded = tokenizer.texts_to_sequences([in_text])[0]
    encoded = pad_sequences([encoded], maxlen=max_length, padding='pre')
    y2,yi = model.predict(encoded, verbose=0)
    y2_max = np.argmax(y2, axis = 1)
    y2_max = int(y2_max)
    yi_max = np.argmax(yi, axis = 1)
    yi_max = int(yi_max)
    out_word = ''
    for i in range(len(df2['cluster_no'])):
      if(y2_max==df2['cluster_no'][i] and yi_max==df2['cluster_index'][i]):
        out_word = df2['words'][i]
        break 
    in_text += ' ' + out_word + ', cluster no = ' + str(y2_max) + ', index of cluster no = ' + str(yi_max)
  return in_text

In [ ]:
data.head(20)

sentences
0                 i do n't want to
1                at the end of the
2               i do n't know what
3               you do n't have to
4                 i do n't know if
5             in the middle of the
6               you do n't want to
7                i do n't know how
8                i do n't think it
9              i do n't think that
10  president of the united states
11               i do n't think so
12              there are a lot of
13                i do n't think i
14           for the first time in
15      what are you talking about
16               i did n't want to
17           the other side of the
18         what are you doing here
19               do n't want to be

In [ ]:
seed_text ='there are a lot'
max_length = 5

get_cluster_LastWord(model, tokenizer,max_length,seed_text, 1)

/usr/local/lib/python3.7/dist-packages/keras/engine/training_v1.py:2079: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


'there are a lot understand, cluster no = 0, index of cluster no = 0'

In [ ]:
def get_cluster_LastWord(model, tokenizer, max_length, seed_text, n_words):
  in_text = seed_text
  for _ in range(n_words):
    encoded = tokenizer.texts_to_sequences([in_text])[0]
    encoded = pad_sequences([encoded], maxlen=max_length, padding='pre')
    y2,yi = model.predict(encoded, verbose=0)
    y2_max = np.argmax(y2, axis = 1)
    y2_max = int(y2_max)
    yi_max = np.argmax(yi, axis = 1)
    yi_max = int(yi_max)
    out_word = ''
    for word, index in tokenizer.word_index.items():
      if index == yi_max:
        out_word = word
        break
    y2_max = int(y2_max)    
    in_text += ' ' + out_word + ', cluster no = ' + str(y2_max) + ', word index of cluster no = ' + str(index)
  return in_text

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df2 = pd.read_csv("/content/new_same_numberwords_clu.csv")

FileNotFoundError: ignored

In [ ]:
df2

In [ ]:
index=[]
for i in range(145):
  c=0
  for j in df2['cluster_no']:
    if(j==i):
      index.append(c)
      c=c+1
len(index)

In [ ]:
index = np.array(index)
index.shape

In [ ]:
df2['cluster_index'] = index

In [ ]:
df2.head(65)

In [ ]:
l=[]
ci=[]
for i in last_word:
  for j in range(len(df2['words'])):
    if(i==df2['words'][j]):
      l.append(df2['cluster_no'][j])
    if(i==df2['words'][j]):
      ci.append(df2['cluster_index'][j])  

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
data = pd.read_csv("/content/2021-11-17, 1847.csv")


In [ ]:
data

In [ ]:
from past.builtins import xrange


In [ ]:
tons = list(xrange(1008))


In [ ]:
tons

In [ ]:
df = pd.read_csv("/content/2021-11-17, 1847.csv", names=tons)


In [ ]:
df

In [ ]:
df.to_csv("new.csv", index = None)

In [ ]:
df2 = pd.read_csv("/content/new.csv")


In [ ]:
df2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import pickle 

In [ ]:
DATA_PATH = "/content"


In [ ]:
infile = open(DATA_PATH+'/versign_segment.pkl','rb')

In [ ]:
best_model2 = pickle.load(infile)


In [ ]:
best_model2

In [ ]:
len(best_model2)

In [ ]:
file_name = "/content/versign_segment.pkl"

open_file = open(file_name, "wb")
pickle.dump(file_name, open_file)
open_file.close()

open_file = open(file_name, "rb")
loaded_list = pickle.load(open_file)
open_file.close()

In [ ]:
loaded_list